apiVersion: v1
kind: Service
metadata:
  name: {{ include "perfsonar.fullname" . }}
  labels:
    {{- include "perfsonar.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
  selector:
    {{- include "perfsonar.selectorLabels" . | nindent 4 }}
