apiVersion: v1
kind: Service
metadata:
  name: {{ include "perfsonar.fullname" . }}
  labels:
    {{- include "perfsonar.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "perfsonar.selectorLabels" . | nindent 4 }}
