apiVersion: v1
kind: Service
metadata:
  name: perfsonar-loadbalancer
  labels:
    {{- include "perfsonar.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 861
      targetPort: 861
      protocol: TCP
      name: owamp

    - port: 8760
      targetPort: 8760
      protocol: TCP
      name: owamp8760

    - port: 8760
      targetPort: 8760
      protocol: UDP
      name: owampudp8760

    - port: 862
      targetPort: 862
      protocol: TCP
      name: twamp

    - port: 18760
      targetPort: 18760
      protocol: TCP
      name: twamptcp18760

    - port: 18760
      targetPort: 18760
      protocol: UDP
      name: twampudp18760

    - port: 5890
      targetPort: 5890
      protocol: TCP
      name: simplestream

    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: nuttcp5000

    - port: 5101
      targetPort: 5101
      protocol: TCP
      name: nuttcp5101

    - port: 5201
      targetPort: 5201
      protocol: TCP
      name: iperf3

    - port: 123
      targetPort: 123
      protocol: UDP
      name: ntp
  selector:
    {{- include "perfsonar.selectorLabels" . | nindent 4 }}
