apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  {{- if and (.Values.persistence.storageClass) (ne "-" .Values.persistence.storageClass) }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
