name: Multi-platform Docker Image Push

# Controls when the workflow will run
on:
  push:
    branches: [ '*' ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ 'master' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_BASE: 'perfsonar/testpoint'
  BUILD_DIR: .

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
        include:
          - platform: linux/amd64
            runs_on: ubuntu-latest
            suffix_tag: amd64
          - platform: linux/arm64
            runs_on: ubuntu-24.04-arm
            suffix_tag: arm64
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runs_on }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
  
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}
        tags: |
          type=schedule,suffix=-${{ matrix.suffix_tag }}
          type=ref,event=branch,suffix=-${{ matrix.suffix_tag }}
          type=ref,event=tag,suffix=-${{ matrix.suffix_tag }}
          type=ref,event=pr,suffix=-${{ matrix.suffix_tag }}
          type=raw,value=latest-${{ matrix.suffix_tag }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Extract Systemd Docker metadata
      id: metasysd
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}
        tags: |
          type=schedule,suffix=-systemd-${{ matrix.suffix_tag }}
          type=ref,event=branch,suffix=-systemd-${{ matrix.suffix_tag }}
          type=ref,event=tag,suffix=-systemd-${{ matrix.suffix_tag }}
          type=ref,event=pr,suffix=-systemd-${{ matrix.suffix_tag }}
          type=raw,value=systemd-${{ matrix.suffix_tag }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker images
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.BUILD_DIR }}
        file: ${{ env.BUILD_DIR }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ matrix.platform }}

    - name: Build and push Systemd Docker images
      id: build-and-push-systemd
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.BUILD_DIR }}
        file: ${{ env.BUILD_DIR }}/systemd/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.metasysd.outputs.tags }}
        labels: ${{ steps.metasysd.outputs.labels }}
        platforms: ${{ matrix.platform }}

  manifest_metadata:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.manifest_meta.outputs.tags }}
      manifest_sysd: ${{ steps.manifest_sysd_meta.outputs.tags }}
    steps:
    - name: Extract Docker metadata for manifest
      id: manifest_meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
    - name: Extract Docker metadata for systemd manifest
      id: manifest_sysd_meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}
        tags: |
          type=schedule,suffix=-systemd
          type=ref,event=branch,suffix=-systemd
          type=ref,event=tag,suffix=-systemd
          type=ref,event=pr,suffix=-systemd
          type=raw,value=systemd,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

  create_manifest:
    strategy:
      matrix:
        tags: ${{ needs.manifest_metadata_sysd.outputs.manifest }}

    runs-on: ubuntu-latest
    needs: 
      - build
      - manifest_metadata
    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create manifest
      run: |
        docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }}-amd64 \
          ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }}-arm64
        docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }}

  create_sysd_manifest:
    strategy:
      matrix:
        tags: ${{ needs.manifest_metadata.outputs.manifest_sysd }}

    runs-on: ubuntu-latest
    needs: 
      - build
      - manifest_metadata
    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create manifest
      run: |
        docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }}-amd64 \
          ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }}-arm64
        docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ matrix.tags }}